version: '3.3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
    - "27017:27017"
    - "27018:27018"
    - "27019:27019"
    restart: always
  mdr:
    depends_on:
      - mongo
    image: microbo/mongodatarest:latest
    ports:
      - "8000:8080"
    restart: always
